// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NuestrasCuentitas.Bitacora.DataAccess.EntityFramework.Persistence;

#nullable disable

namespace NuestrasCuentitas.Bitacora.DataAccess.EntityFramework.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409185502_InitialCore")]
    partial class InitialCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.AccessAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PseudonymId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pseudonym_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trace_id");

                    b.HasKey("AuditId");

                    b.HasIndex("PatientId", "CreatedAtUtc");

                    b.ToTable("access_audits", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.ConsentGrant", b =>
                {
                    b.Property<Guid>("ConsentGrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consent_grant_id");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("consent_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ConsentGrantId");

                    b.HasIndex("PatientId", "ConsentVersion");

                    b.ToTable("consent_grants", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.DailyCheckin", b =>
                {
                    b.Property<Guid>("DailyCheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("daily_checkin_id");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date")
                        .HasColumnName("checkin_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EncryptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encrypted_at");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_payload");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SafeProjection")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("safe_projection");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DailyCheckinId");

                    b.HasIndex("PatientId", "CheckinDate")
                        .IsUnique();

                    b.ToTable("daily_checkins", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.EncryptionKeyVersion", b =>
                {
                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeyVersion"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("KeyVersion");

                    b.ToTable("encryption_key_versions", (string)null);

                    b.HasData(
                        new
                        {
                            KeyVersion = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("MoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mood_entry_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EncryptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encrypted_at");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_payload");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SafeProjection")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("safe_projection");

                    b.HasKey("MoodEntryId");

                    b.HasIndex("PatientId", "CreatedAtUtc");

                    b.ToTable("mood_entries", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.PendingInvite", b =>
                {
                    b.Property<Guid>("PendingInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pending_invite_id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invite_token");

                    b.Property<string>("InviteeEmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invitee_email_hash");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("PendingInviteId");

                    b.HasIndex("ProfessionalId", "InviteeEmailHash", "Status");

                    b.ToTable("pending_invites", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email_hash");

                    b.Property<byte[]>("EncryptedEmail")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_email");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("SessionsRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sessions_revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supabase_user_id");

                    b.HasKey("UserId");

                    b.HasIndex("EmailHash");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
