// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NuestrasCuentitas.Bitacora.DataAccess.EntityFramework.Persistence;

#nullable disable

namespace NuestrasCuentitas.Bitacora.DataAccess.EntityFramework.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.AccessAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PseudonymId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pseudonym_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid")
                        .HasColumnName("trace_id");

                    b.HasKey("AuditId");

                    b.HasIndex("PatientId", "CreatedAtUtc");

                    b.ToTable("access_audits", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.BindingCode", b =>
                {
                    b.Property<Guid>("BindingCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("binding_code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("TtlPreset")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ttl_preset");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.HasKey("BindingCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProfessionalId", "Used", "ExpiresAt");

                    b.ToTable("binding_codes", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.CareLink", b =>
                {
                    b.Property<Guid>("CareLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("care_link_id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<bool>("CanViewData")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view_data");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("CareLinkId");

                    b.HasIndex("PatientId", "ProfessionalId");

                    b.HasIndex("ProfessionalId", "Status");

                    b.ToTable("care_links", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.ConsentGrant", b =>
                {
                    b.Property<Guid>("ConsentGrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consent_grant_id");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("consent_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("ConsentGrantId");

                    b.HasIndex("PatientId", "ConsentVersion");

                    b.ToTable("consent_grants", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.DailyCheckin", b =>
                {
                    b.Property<Guid>("DailyCheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("daily_checkin_id");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date")
                        .HasColumnName("checkin_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EncryptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encrypted_at");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_payload");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SafeProjection")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("safe_projection");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DailyCheckinId");

                    b.HasIndex("PatientId", "CheckinDate")
                        .IsUnique();

                    b.ToTable("daily_checkins", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.EncryptionKeyVersion", b =>
                {
                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeyVersion"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("KeyVersion");

                    b.ToTable("encryption_key_versions", (string)null);

                    b.HasData(
                        new
                        {
                            KeyVersion = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("MoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mood_entry_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EncryptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encrypted_at");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_payload");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SafeProjection")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("safe_projection");

                    b.HasKey("MoodEntryId");

                    b.HasIndex("PatientId", "CreatedAtUtc");

                    b.ToTable("mood_entries", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.PendingInvite", b =>
                {
                    b.Property<Guid>("PendingInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pending_invite_id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invite_token");

                    b.Property<string>("InviteeEmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invitee_email_hash");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("PendingInviteId");

                    b.HasIndex("ProfessionalId", "InviteeEmailHash", "Status");

                    b.ToTable("pending_invites", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.ReminderConfig", b =>
                {
                    b.Property<Guid>("ReminderConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_config_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("HourUtc")
                        .HasColumnType("integer")
                        .HasColumnName("hour_utc");

                    b.Property<int>("MinuteUtc")
                        .HasColumnType("integer")
                        .HasColumnName("minute_utc");

                    b.Property<DateTime?>("NextFireAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_fire_at_utc");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("ReminderConfigId");

                    b.HasIndex("NextFireAtUtc");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("reminder_configs", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.TelegramPairingCode", b =>
                {
                    b.Property<Guid>("TelegramPairingCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_pairing_code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.HasKey("TelegramPairingCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PatientId", "Used", "ExpiresAt");

                    b.ToTable("telegram_pairing_codes", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.TelegramSession", b =>
                {
                    b.Property<Guid>("TelegramSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("telegram_session_id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chat_id");

                    b.Property<int>("ConversationState")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_state");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at_utc");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PendingFactorsJson")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pending_factors_json");

                    b.Property<int?>("PendingMoodScore")
                        .HasColumnType("integer")
                        .HasColumnName("pending_mood_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UnlinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlinked_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TelegramSessionId");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasFilter("status = 'Linked'");

                    b.HasIndex("PatientId", "Status");

                    b.ToTable("telegram_sessions", (string)null);
                });

            modelBuilder.Entity("NuestrasCuentitas.Bitacora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email_hash");

                    b.Property<byte[]>("EncryptedEmail")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_email");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("SessionsRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sessions_revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth_subject");

                    b.HasKey("UserId");

                    b.HasIndex("EmailHash");

                    b.HasIndex("AuthSubject")
                        .IsUnique()
                        .HasDatabaseName("IX_users_auth_subject");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
